theme: jekyll-theme-cayman
title: "Towards Photographic Image Manipulation with Balanced Growing of Generative Autoencoders"
description: "Ari Heljakka, Arno Solin, Juho Kannala<br />"
markdown: kramdown